#pragma once
#include <cstdint>
#include <glad/glad.h>

namespace agl
{
	enum texture_pixel_match : std::uint32_t
	{
		TEXTURE_PIXEL_NONE = 0,
		TEXTURE_PIXEL_NEAREST = GL_NEAREST,
		TEXTURE_PIXEL_LINEAR = GL_LINEAR,
		TEXTURE_PIXEL_NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
		TEXTURE_PIXEL_LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
		TEXTURE_PIXEL_NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
		TEXTURE_PIXEL_LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR
	};
}

