#pragma once
#include <cstdint>
#include <glad/glad.h>

namespace agl
{
	enum gl_buffer_usage : std::uint32_t
	{
		BUFFER_DYNAMIC_COPY = GL_DYNAMIC_COPY,
		BUFFER_DYNAMIC_DRAW = GL_DYNAMIC_DRAW,
		BUFFER_DYNAMIC_READ = GL_DYNAMIC_READ,
		BUFFER_STATIC_COPY = GL_STATIC_COPY,
		BUFFER_STATIC_DRAW = GL_STATIC_DRAW,
		BUFFER_STATIC_READ = GL_STATIC_READ,
		BUFFER_STREAM_COPY = GL_STREAM_COPY,
		BUFFER_STREAM_DRAW = GL_STREAM_DRAW,
		BUFFER_STREAM_READ = GL_STREAM_READ,
	};
}



