#pragma once
#include <cstdint>
#include <glad/glad.h>

namespace agl
{
	enum gl_blend_function : std::uint32_t
	{
		BLEND_FUNC_ZERO = GL_ZERO,
		BLEND_FUNC_ONE = GL_ONE,
		BLEND_FUNC_SRC_COLOR = GL_SRC_COLOR,
		BLEND_FUNC_ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR,
		BLEND_FUNC_DST_COLOR = GL_DST_COLOR,
		BLEND_FUNC_ONE_MINUS_DST_COLOR = GL_ONE_MINUS_DST_COLOR,
		BLEND_FUNC_SRC_ALPHA = GL_SRC_ALPHA,
		BLEND_FUNC_ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA,
		BLEND_FUNC_DST_ALPHA = GL_DST_ALPHA,
		BLEND_FUNC_ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA,
		BLEND_FUNC_CONSTANT_COLOR = GL_CONSTANT_COLOR,
		BLEND_FUNC_ONE_MINUS_CONSTANT_COLOR = GL_ONE_MINUS_CONSTANT_COLOR,
		BLEND_FUNC_CONSTANT_ALPHA = GL_CONSTANT_ALPHA,
		BLEND_FUNC_ONE_MINUS_CONSTANT_ALPHA = GL_ONE_MINUS_CONSTANT_ALPHA,
		BLEND_FUNC_SRC_ALPHA_SATURATE = GL_SRC_ALPHA_SATURATE,
		BLEND_FUNC_SRC1_COLOR = GL_SRC1_COLOR,
		BLEND_FUNC_ONE_MINUS_SRC1_COLOR = GL_ONE_MINUS_SRC1_COLOR,
		BLEND_FUNC_SRC1_ALPHA = GL_SRC1_ALPHA,
		BLEND_FUNC_ONE_MINUS_SRC1_ALPHA = GL_ONE_MINUS_SRC1_ALPHA
	};
}

